# IT 314 Software Engineering
## Lab 5

### Name: Prajapati Vrutik Navneetbhai
### Student ID: 202001124
<hr>

### Static Code Analysis of a git repository using [mypy](https://mypy.readthedocs.io/en/stable/) tool

### Reference Git Repository: https://github.com/vrutik2809/Django-Blog

## mypy tool:
- mypy is an open-source static type checker for Python.
- It supports type annotations for function arguments, return values, and variables.
- It can also check for common type-related errors such as type mismatches, invalid method calls, and incorrect argument types.
- mypy supports various types of annotations including built-in types like str, int, float, etc., user-defined classes, generic types, and union types.
- It also provides options to customize the checking process, ignore certain files, and suppress specific error messages.

## Process:
1. install mypy using command: `python -m pip install mypy`
2. clone the git repository <br>
![image6](https://user-images.githubusercontent.com/74986666/225573982-74d41f4c-f1e7-49e6-aea4-042d3eeccf69.png)
3. running command for code analysis: `python -m mypy <path_of_file>` <br>
![image3](https://user-images.githubusercontent.com/74986666/225574458-599ec801-0fbf-424f-add0-08f0ce851269.png) <br>
the above error shows that some moduels are not found <br> <br>
![image2](https://user-images.githubusercontent.com/74986666/225574446-0a30f9d6-8f06-4740-ab1c-3e8c71122890.png) <br>
the above error shows that some variables are not defined <br> <br>
![image4](https://user-images.githubusercontent.com/74986666/225574494-1d763197-b671-400c-bea5-9eb281c0c0ea.png) <br>
the above error shows that some moduels are not found <br> <br>
![image1](https://user-images.githubusercontent.com/74986666/225574641-9f31e3a4-72ef-493e-be5a-2ff75b772b58.png) <br>
the above screenshot shows that there is no error in `settings.py` file <br> <br>
![image5](https://user-images.githubusercontent.com/74986666/225574549-16f737fc-6916-4e1b-bdf9-7ff8f3ed20e7.png) <br>
the above screenshot shows that there is no error in `asgi.py` file


